// ClickPIP — Mockup Data

import type {
  User,
  Department,
  PIPRecord,
  CheckIn,
  Comment,
  DashboardStats,
} from "./types";

// Current logged-in user (mockup)
export const currentUser: User = {
  id: "u1",
  name: "สมศรี จันทร์สว่าง",
  email: "somsri@clickbroker.co.th",
  role: "admin",
  department: "ฝ่ายทรัพยากรบุคคล",
  position: "HR Manager",
  avatarUrl: "",
  managerId: null,
};

export const mockUsers: User[] = [
  currentUser,
  {
    id: "u2",
    name: "วิชัย สุขใจ",
    email: "wichai@clickbroker.co.th",
    role: "manager",
    department: "ฝ่ายขาย",
    position: "Sales Manager",
    avatarUrl: "",
    managerId: "u1",
  },
  {
    id: "u3",
    name: "สมชาย มั่นคง",
    email: "somchai@clickbroker.co.th",
    role: "employee",
    department: "ฝ่ายขาย",
    position: "Sales Executive",
    avatarUrl: "",
    managerId: "u2",
  },
  {
    id: "u4",
    name: "นภา แสงทอง",
    email: "napa@clickbroker.co.th",
    role: "employee",
    department: "ฝ่ายขาย",
    position: "Sales Executive",
    avatarUrl: "",
    managerId: "u2",
  },
  {
    id: "u5",
    name: "ธนา เจริญสุข",
    email: "tana@clickbroker.co.th",
    role: "manager",
    department: "ฝ่ายปฏิบัติการ",
    position: "Operations Manager",
    avatarUrl: "",
    managerId: "u1",
  },
  {
    id: "u6",
    name: "พรทิพย์ รักดี",
    email: "porntip@clickbroker.co.th",
    role: "employee",
    department: "ฝ่ายปฏิบัติการ",
    position: "Operations Staff",
    avatarUrl: "",
    managerId: "u5",
  },
  {
    id: "u7",
    name: "อนุชา วงศ์ดี",
    email: "anucha@clickbroker.co.th",
    role: "employee",
    department: "ฝ่ายการตลาด",
    position: "Marketing Executive",
    avatarUrl: "",
    managerId: "u5",
  },
  {
    id: "u8",
    name: "กมล ศรีสุข",
    email: "kamol@clickbroker.co.th",
    role: "super_admin",
    department: "ฝ่ายบริหาร",
    position: "CEO",
    avatarUrl: "",
    managerId: null,
  },
];

export const mockDepartments: Department[] = [
  { id: "d1", name: "ฝ่ายขาย", managerId: "u2" },
  { id: "d2", name: "ฝ่ายปฏิบัติการ", managerId: "u5" },
  { id: "d3", name: "ฝ่ายทรัพยากรบุคคล", managerId: "u1" },
  { id: "d4", name: "ฝ่ายการตลาด", managerId: "u5" },
  { id: "d5", name: "ฝ่ายบริหาร", managerId: "u8" },
];

export const mockPIPs: PIPRecord[] = [
  {
    id: "pip1",
    employeeId: "u3",
    employeeName: "สมชาย มั่นคง",
    employeeDepartment: "ฝ่ายขาย",
    employeePosition: "Sales Executive",
    managerId: "u2",
    managerName: "วิชัย สุขใจ",
    status: "active",
    duration: 60,
    startDate: "2026-01-15",
    endDate: "2026-03-15",
    reason: "ยอดขายต่ำกว่าเป้าหมาย 3 เดือนติดต่อกัน ไม่ถึง 50% ของเป้าที่กำหนด",
    goals: [
      {
        id: "g1",
        pipId: "pip1",
        title: "เพิ่มยอดขายรายเดือน",
        description: "ปิดการขายกรมธรรม์ประกันภัยให้ได้ตามเป้า",
        kpiTarget: "ยอดขาย",
        kpiUnit: "บาท",
        currentValue: 180000,
        targetValue: 300000,
        rating: null,
        status: "in_progress",
      },
      {
        id: "g2",
        pipId: "pip1",
        title: "เพิ่มจำนวนลูกค้าใหม่",
        description: "หาลูกค้าใหม่ผ่านช่องทาง online และ offline",
        kpiTarget: "จำนวนลูกค้าใหม่",
        kpiUnit: "ราย",
        currentValue: 8,
        targetValue: 15,
        rating: null,
        status: "in_progress",
      },
      {
        id: "g3",
        pipId: "pip1",
        title: "พัฒนาทักษะการนำเสนอ",
        description: "เข้าอบรมการขายและฝึกนำเสนอกับหัวหน้า",
        kpiTarget: "ชั่วโมงอบรม",
        kpiUnit: "ชั่วโมง",
        currentValue: 6,
        targetValue: 12,
        rating: null,
        status: "in_progress",
      },
    ],
    overallRating: null,
    result: null,
    resultNote: null,
    createdAt: "2026-01-14",
    updatedAt: "2026-02-18",
  },
  {
    id: "pip2",
    employeeId: "u4",
    employeeName: "นภา แสงทอง",
    employeeDepartment: "ฝ่ายขาย",
    employeePosition: "Sales Executive",
    managerId: "u2",
    managerName: "วิชัย สุขใจ",
    status: "active",
    duration: 30,
    startDate: "2026-02-01",
    endDate: "2026-03-03",
    reason: "อัตราการติดตามลูกค้าต่ำ ไม่มีการ follow up ลูกค้าที่สนใจ ทำให้เสียโอกาสขาย",
    goals: [
      {
        id: "g4",
        pipId: "pip2",
        title: "เพิ่มอัตราการติดตามลูกค้า",
        description: "ติดตามลูกค้าที่สนใจภายใน 24 ชั่วโมง",
        kpiTarget: "อัตรา follow up",
        kpiUnit: "%",
        currentValue: 65,
        targetValue: 90,
        rating: null,
        status: "in_progress",
      },
      {
        id: "g5",
        pipId: "pip2",
        title: "ปรับปรุงการบันทึกข้อมูลลูกค้า",
        description: "บันทึกข้อมูลลูกค้าใน CRM ให้ครบถ้วนทุกราย",
        kpiTarget: "ความครบถ้วน CRM",
        kpiUnit: "%",
        currentValue: 70,
        targetValue: 100,
        rating: null,
        status: "in_progress",
      },
    ],
    overallRating: null,
    result: null,
    resultNote: null,
    createdAt: "2026-01-31",
    updatedAt: "2026-02-15",
  },
  {
    id: "pip3",
    employeeId: "u6",
    employeeName: "พรทิพย์ รักดี",
    employeeDepartment: "ฝ่ายปฏิบัติการ",
    employeePosition: "Operations Staff",
    managerId: "u5",
    managerName: "ธนา เจริญสุข",
    status: "completed",
    duration: 90,
    startDate: "2025-10-01",
    endDate: "2025-12-30",
    reason: "การประมวลผลเอกสารล่าช้า ข้อผิดพลาดในการคีย์ข้อมูลสูงเกินมาตรฐาน",
    goals: [
      {
        id: "g6",
        pipId: "pip3",
        title: "ลดเวลาประมวลผลเอกสาร",
        description: "ประมวลผลเอกสารให้เสร็จภายใน 2 วันทำการ",
        kpiTarget: "เวลาเฉลี่ย",
        kpiUnit: "วัน",
        currentValue: 1.5,
        targetValue: 2,
        rating: 4,
        status: "achieved",
      },
      {
        id: "g7",
        pipId: "pip3",
        title: "ลดอัตราข้อผิดพลาด",
        description: "ลดข้อผิดพลาดในการคีย์ข้อมูลให้ต่ำกว่า 2%",
        kpiTarget: "อัตราข้อผิดพลาด",
        kpiUnit: "%",
        currentValue: 1.5,
        targetValue: 2,
        rating: 5,
        status: "achieved",
      },
    ],
    overallRating: 4,
    result: "passed",
    resultNote: "พนักงานพัฒนาตัวเองได้ดี ผลงานดีขึ้นอย่างเห็นได้ชัด",
    createdAt: "2025-09-30",
    updatedAt: "2025-12-30",
  },
  {
    id: "pip4",
    employeeId: "u7",
    employeeName: "อนุชา วงศ์ดี",
    employeeDepartment: "ฝ่ายการตลาด",
    employeePosition: "Marketing Executive",
    managerId: "u5",
    managerName: "ธนา เจริญสุข",
    status: "failed",
    duration: 60,
    startDate: "2025-11-01",
    endDate: "2025-12-31",
    reason: "ผลงาน content marketing ต่ำกว่ามาตรฐาน engagement rate ไม่ถึงเป้า",
    goals: [
      {
        id: "g8",
        pipId: "pip4",
        title: "เพิ่ม engagement rate",
        description: "เพิ่ม engagement rate ของ social media content",
        kpiTarget: "Engagement rate",
        kpiUnit: "%",
        currentValue: 1.8,
        targetValue: 3.5,
        rating: 2,
        status: "not_achieved",
      },
      {
        id: "g9",
        pipId: "pip4",
        title: "เพิ่มจำนวน leads จาก content",
        description: "สร้าง content ที่ดึงดูด leads เข้ามาในระบบ",
        kpiTarget: "จำนวน leads",
        kpiUnit: "ราย",
        currentValue: 12,
        targetValue: 30,
        rating: 1,
        status: "not_achieved",
      },
    ],
    overallRating: 2,
    result: "failed",
    resultNote: "พนักงานไม่สามารถพัฒนาผลงานได้ตามเป้าหมาย แนะนำพิจารณาย้ายแผนกหรือดำเนินการตามนโยบายบริษัท",
    createdAt: "2025-10-31",
    updatedAt: "2025-12-31",
  },
  {
    id: "pip5",
    employeeId: "u3",
    employeeName: "สมชาย มั่นคง",
    employeeDepartment: "ฝ่ายขาย",
    employeePosition: "Sales Executive",
    managerId: "u2",
    managerName: "วิชัย สุขใจ",
    status: "pending",
    duration: 30,
    startDate: "2026-03-01",
    endDate: "2026-03-31",
    reason: "ต่ออายุ PIP รอบที่ 2 หลังจาก PIP รอบแรกยังไม่ถึงเป้า",
    goals: [],
    overallRating: null,
    result: null,
    resultNote: null,
    createdAt: "2026-02-19",
    updatedAt: "2026-02-19",
  },
];

export const mockCheckIns: CheckIn[] = [
  {
    id: "ci1",
    pipId: "pip1",
    weekNumber: 1,
    date: "2026-01-22",
    managerNote: "สมชายเริ่มปรับตัวได้ดี มีการวางแผนการขายเป็นระบบมากขึ้น",
    employeeNote: "เริ่มใช้ระบบ CRM ในการติดตามลูกค้า รู้สึกว่าช่วยให้จัดการได้ดีขึ้น",
    goalUpdates: [
      { goalId: "g1", previousValue: 100000, currentValue: 120000, note: "ปิดการขายได้ 3 ราย" },
      { goalId: "g2", previousValue: 3, currentValue: 5, note: "หาลูกค้าใหม่ได้ 2 ราย" },
      { goalId: "g3", previousValue: 0, currentValue: 3, note: "เข้าอบรม Sales Technique" },
    ],
    createdBy: "u2",
  },
  {
    id: "ci2",
    pipId: "pip1",
    weekNumber: 2,
    date: "2026-01-29",
    managerNote: "ยอดขายเพิ่มขึ้นต่อเนื่อง แต่ยังต้องพัฒนาทักษะการปิดการขาย",
    employeeNote: "พยายามติดต่อลูกค้ามากขึ้น แต่ยังปิดการขายไม่ค่อยได้",
    goalUpdates: [
      { goalId: "g1", previousValue: 120000, currentValue: 145000, note: "ปิดการขายเพิ่ม 2 ราย" },
      { goalId: "g2", previousValue: 5, currentValue: 6, note: "ลูกค้าใหม่ 1 ราย" },
      { goalId: "g3", previousValue: 3, currentValue: 4, note: "ฝึก role-play กับหัวหน้า 1 ชม." },
    ],
    createdBy: "u2",
  },
  {
    id: "ci3",
    pipId: "pip1",
    weekNumber: 3,
    date: "2026-02-05",
    managerNote: "เห็นพัฒนาการที่ดี สมชายมีความมั่นใจในการนำเสนอมากขึ้น",
    employeeNote: "เริ่มมั่นใจมากขึ้น ลูกค้าตอบรับดี",
    goalUpdates: [
      { goalId: "g1", previousValue: 145000, currentValue: 180000, note: "เดือนนี้ดีขึ้นมาก" },
      { goalId: "g2", previousValue: 6, currentValue: 8, note: "ลูกค้าใหม่จาก referral 2 ราย" },
      { goalId: "g3", previousValue: 4, currentValue: 6, note: "เข้าอบรม Closing Technique" },
    ],
    createdBy: "u2",
  },
];

export const mockComments: Comment[] = [
  {
    id: "c1",
    pipId: "pip1",
    userId: "u2",
    userName: "วิชัย สุขใจ",
    userRole: "manager",
    content: "สมชาย ขอให้ focus ที่การ follow up ลูกค้าเก่าด้วยนะครับ ไม่ใช่แค่หาลูกค้าใหม่",
    createdAt: "2026-02-10T10:30:00",
  },
  {
    id: "c2",
    pipId: "pip1",
    userId: "u3",
    userName: "สมชาย มั่นคง",
    userRole: "employee",
    content: "รับทราบครับ จะปรับแผนเพิ่มการ follow up ลูกค้าเดิมด้วย",
    createdAt: "2026-02-10T11:15:00",
  },
  {
    id: "c3",
    pipId: "pip1",
    userId: "u1",
    userName: "สมศรี จันทร์สว่าง",
    userRole: "admin",
    content: "แนะนำให้จัด weekly coaching session เพิ่มเติมด้วยค่ะ",
    createdAt: "2026-02-12T09:00:00",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalActive: 2,
  totalCompleted: 1,
  totalFailed: 1,
  totalPending: 1,
  nearDeadline: 1,
  passRate: 50,
};
